 <!--  Thanks for sending a pull request!  Here are some tips for you:

1. If this is your first time, please read our contributor guidelines: https://github.com/istio-ecosystem/sail-operator/blob/main/CONTRIBUTING.md
2. Discuss your changes before you start working on them. You can open a new issue in the [Sail Operator GitHub repository](https://github.com/istio-ecosystem/sail-operator/issues) or start a discussion in the [Sail Operator Discussion](https://github.com/istio-ecosystem/sail-operator/discussions). By this way, you can get feedback from the community and ensure that your changes are aligned with the project goals.
3. Use of Labels: We use labels in the issues to help us track the progress of the issues. You can use the labels to help you understand the status of the issue and what is needed to move forward. Those labels are:
  - `backport/backport-handled`: Use this label to indicate that the issue has been backported to the appropriate branches.
  - `test`: Use this label to indicate that the issue is related to test or add `test-needed` when a issue needs a test to be added related. Can be used in combination with other labels to mark the proper test type, for example: `test-e2e`, `test-unit`, `test-integration`.
  - `good first issue`: Use this label to indicate that the issue is a good first issue for new contributors.
  - `help wanted`: Use this label to indicate that the issue needs help from the community.
  - `enhancement`: Use this label to indicate that the issue is an enhancement related to a new feature or improvement.
4. If the PR is unfinished, make is as draft.
-->

#### What type of PR is this?

[ ] Bugfix - Fix a bug
[ ] Enhancement - New feature or improvement
[ ] Cleanup / Refactor - Any small code cleanups or refactoring
[ ] Dependencies - Updates a dependency file
[ ] Test - Pull request relates to tests
[ ] Documentation - Improvements or additions to documentation

#### What this PR does / why we need it:

#### Which issue(s) this PR fixes:
<!--
*Automatically closes linked issue when PR is merged.
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
-->
Fixes #

#### Special notes for your reviewer:

#### Does this PR introduce a user-facing change?
<!--
If no, just write "NONE" in the release-note block below.
If yes, a release note is required:
Enter your extended release note in the block below. If the PR requires additional action from users switching to the new release, include the string "action required".
-->
```release-note

```

#### Additional documentation:

#### Does this PR introduce a breaking change?

#### Other information:

