name: Publish Helm artifact

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
  workflow_run:
    workflows: ['Release workflow']
    types: [completed]

env:
  GIT_USER: ${{ secrets.GIT_USER }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: ${{ inputs.release_version }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          make helm-artifacts-publish \
            -e GIT_CONFIG_USER_NAME="$GIT_CONFIG_USER_NAME" \
            -e GIT_CONFIG_USER_EMAIL="$GIT_CONFIG_USER_EMAIL" \
            -e OPERATOR_VERSION=$VERSION
        env:
          GIT_CONFIG_USER_NAME: "${{ github.actor }}"
          GIT_CONFIG_USER_EMAIL: "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
