name: Publish Helm artifact

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
  workflow_run:
    workflows: ['Release workflow']
    types: [completed]

env:
  GIT_USER: ${{ secrets.GIT_USER }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: ${{ inputs.release_version }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - run: |
          make helm-artifacts-publish \
            -e OPERATOR_VERSION=$VERSION
