name: Publish Helm artifact

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Release workflow']
    types: [completed]

env:
  GIT_USER: ${{ secrets.GIT_USER }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "test helm artifacts run"
