name: Publish Helm artifact

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
  workflow_run:
    workflows: ["Release workflow"]
    types: [completed]

run-name: Publish Helm artifact ${{ inputs.release_version }}

env:
  GIT_USER: ${{ secrets.GIT_USER }}
  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  VERSION: ${{ inputs.release_version }}

jobs:
  helm:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Download Operator version artifact
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: actions/download-artifact@v4
        with:
          name: operator-version
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GIT_TOKEN }}

      - name: Set VERSION env var if empty
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          if [ -z $VERSION ]; then
            echo "VERSION=$(cat operator-version)" >> $GITHUB_ENV
          fi

      - name: Publish Helm artifact to "gh-pages" branch
        run: |
          make helm-artifacts-publish \
            -e GIT_CONFIG_USER_NAME="$GIT_CONFIG_USER_NAME" \
            -e GIT_CONFIG_USER_EMAIL="$GIT_CONFIG_USER_EMAIL" \
            -e OPERATOR_VERSION="$VERSION"
        env:
          GIT_CONFIG_USER_NAME: "${{ github.actor }}"
          GIT_CONFIG_USER_EMAIL: "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

